name: Deploy Website
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm run build
    - name: Save API Keys to env
      run: |
        echo "MARVEL_API_HASH=${{ secrets.MARVEL_API_HASH }}" >> $GITHUB_ENV
        echo "MARVEL_TIMESTAMP=${{ secrets.MARVEL_TIMESTAMP }}" >> $GITHUB_ENV
        echo "MARVEL_API_KEY=${{ secrets.MARVEL_API_KEY }}" >> $GITHUB_ENV
    - name: Deploy
      run: npm run deploy
